apiVersion: v1
kind: Namespace
metadata:
  name: xyx
  labels:
    name: xyz
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: xyz-be-config
  namespace: xyz
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /xyz/health
    port: 3000