apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: xyz-secrets
spec:
  namespaceSelector: 
    matchLabels:
      kubernetes.io/metadata.name: xyz
  externalSecretName: xyz-secrets
  externalSecretSpec:
    refreshInterval: 2s
    secretStoreRef:
      name: global-secret-store
      kind: ClusterSecretStore
    target:
      name: xyz-secrets
      creationPolicy: Owner
      deletionPolicy: "Delete"
    data:
    - secretKey: SECRET_NAME
      remoteRef:
        key: /conf/xyz/${BUILD_ENV}/SECRET_NAME
    #Repeat the above steps for adding all the required secrets.
    #It is assumed that the secrets are stored in the parameter store of AWS and referenced in the Kubernetes cluster of GKE. 
    #This helps in setting up a multi cluster architecture