apiVersion: v1
kind: Service
metadata:
  name: xyz-svc
  namespace: xyz
  annotations:
    cloud.google.com/backend-config: '{"default": "xyz-be-config"}'
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: xyz
  type: NodePort